#!/bin/bash -e
# initialize wireguard server keys & configuration

. /etc/default/inithooks

[ -e $INITHOOKS_CONF ] && . $INITHOOKS_CONF

# skip initialization if headless (will be configured by turnkey-init)
if [[ -n "$SEC_UPDATES" ]] && [[ -z "$APP_VIRTUAL_SUBNET" ]]; then
    exit 0
fi

$INITHOOKS_PATH/bin/wireguard.py --profile="$APP_PROFILE" --virtual-subnet="$APP_VIRTUAL_SUBNET" --domain="$APP_DOMAIN"
